# Generated by Django 3.0.6 on 2020-06-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='banner_image',
            field=models.ImageField(blank=True, default='default-banner.jpg', upload_to='media_pics/%Y/%m/%d'),
        ),
    ]
