# Generated by Django 3.0.6 on 2020-05-17 15:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeAudience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Challenges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=150)),
                ('offered_by', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, default='default.jpg', upload_to='media_pics/%Y/%m/%d')),
                ('description', models.TextField()),
                ('external_url', models.CharField(max_length=150)),
                ('tags', multiselectfield.db.fields.MultiSelectField(choices=[('Energy', 'Energy'), ('Lifestyle', 'Lifestyle'), ('Technology', 'Technology'), ('Culture', 'Culture'), ('Fashion', 'Fashion'), ('Entertainment', 'Entertainment')], max_length=120)),
                ('rules_of_engagement', models.TextField()),
                ('judging_criteria', models.TextField()),
                ('prize', models.CharField(max_length=150)),
                ('how_to_enter', models.TextField()),
                ('point_of_contact', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('open_until', models.DateTimeField(default=datetime.datetime(2020, 6, 16, 18, 5, 50, 454941))),
                ('targeted_audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ChallengeAudience')),
            ],
        ),
    ]
