# Generated by Django 3.0.6 on 2020-05-17 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200517_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Archived', 'Archived')], default='Open', max_length=200),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='open_until',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 18, 27, 26, 616584)),
        ),
    ]
