# Generated by Django 3.0.6 on 2020-05-19 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20200519_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenges',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='challenges',
            name='is_in_progress',
        ),
        migrations.RemoveField(
            model_name='challenges',
            name='is_open',
        ),
        migrations.AddField(
            model_name='challenges',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Archived', 'Archived')], default='Open', max_length=200),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='open_until',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 18, 15, 7, 23, 999378)),
        ),
    ]
