# Generated by Django 3.0.6 on 2020-05-24 14:05

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20200519_1507'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challenges',
            options={'verbose_name': 'challenge', 'verbose_name_plural': 'challenges'},
        ),
        migrations.AddField(
            model_name='challenges',
            name='challenge_summary',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='how_to_enter',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='judging_criteria',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='open_until',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 23, 17, 5, 6, 376881)),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='rules_of_engagement',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
