# Generated by Django 3.0.6 on 2020-05-28 12:28

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20200524_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preapproved_challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('length', models.CharField(max_length=150)),
                ('short_description', models.TextField()),
                ('steps_to_complete', models.TextField()),
                ('why', models.TextField(blank=True, null=True)),
                ('tips', models.TextField(blank=True, null=True)),
                ('tags', multiselectfield.db.fields.MultiSelectField(choices=[('Energy', 'Energy'), ('Lifestyle', 'Lifestyle'), ('Technology', 'Technology'), ('Culture', 'Culture'), ('Fashion', 'Fashion'), ('Entertainment', 'Entertainment')], max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='challenges',
            name='open_until',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 27, 15, 28, 24, 148552)),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Archived', 'Archived'), ('Rolling', 'Rolling')], default='Open', max_length=200),
        ),
    ]
