# Generated by Django 3.0.6 on 2020-05-29 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20200528_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='open_until',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 28, 8, 57, 57, 944614)),
        ),
    ]
