# Generated by Django 3.0.6 on 2020-06-01 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20200601_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='open_until',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 11, 41, 9, 519369)),
        ),
        migrations.RemoveField(
            model_name='challenges',
            name='tags',
        ),
        migrations.AddField(
            model_name='challenges',
            name='tags',
            field=models.ManyToManyField(to='mainapp.ChallengeTag'),
        ),
    ]
