# Generated by Django 3.0.6 on 2020-06-02 05:37

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_auto_20200602_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='date_posted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='open_until',
            field=models.DateField(default=datetime.datetime(2020, 7, 2, 8, 37, 31, 176801)),
        ),
    ]
